### ISSUE TITLE
Insert Statements Do Not Stringify

### ISSUE THREAD

**Issue by Crowes** [Sugarcoated/Fondant#5]
When writing an INSERT statement, the `Sequence` instance will not stringify on `.toString()`, reporting this:

```
Error: Cannot generate without expressor
    at SequencePart.generate (V:\Github\Gallink\Joints\node_modules\@sugarcoated\fondant-sequence\SequencePart.js:102:41)
    at _stringify (V:\Github\Gallink\Joints\node_modules\@sugarcoated\fondant-sequence\Sequence.js:598:28)
    at Array.map (native)
    at Sequence.toString (V:\Github\Gallink\Joints\node_modules\@sugarcoated\fondant-sequence\Sequence.js:509:44)
    at Object.queryQueue.add [as promiseGenerator] (V:\Github\Gallink\Joints\providers\Database.js:55:44)
    at Queue._dequeue (V:\Github\Gallink\Joints\node_modules\promise-queue\lib\index.js:149:30)
    at V:\Github\Gallink\Joints\node_modules\promise-queue\lib\index.js:108:18
    at Promise (<anonymous>)
    at Queue.add (V:\Github\Gallink\Joints\node_modules\promise-queue\lib\index.js:93:16)
    at DatabaseModel.query (V:\Github\Gallink\Joints\providers\Database.js:54:23)
```

**Comment by Crowes** [comment]
This is because, in certain case, no expressor is actually needed. `DELETE` statements being one, `INSERT` another. The solution to this was to default the expressor of every `SequencePart` , or allow the `.toString()` method to handle that `function` not being there; both handle this error silently.
